[project]
name = "agent-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "dotenv>=0.9.9",
    "fastapi>=0.142.2",
    "jupyter>=1.1.1",
    "ipykernel>=7.4.0",
    "loguru>=0.7.3",
    "mistralai>=3.0.0",
    "notebook>=7.6.3",
    "openai>=3.24.0",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pypdf2>=3.0.1",
    "sentence-transformers>=6.1.0",
    "uvicorn>=0.54.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
